import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(scriptDir, "..");
const sourcePath = path.join(root, "source", "openusd_api_overview_and_purpose_source.html");
const siteDir = path.join(root, "site");
const outputPath = path.join(siteDir, "_usd__overview_and_purpose.html");

function bilingualBlock(zh, enHtml) {
  return `<div class="bilingual-block"><p class="zh">${zh}</p><p class="en">${enHtml}</p></div>`;
}

function bilingualLi(zh, enHtml) {
  return `<li class="bilingual-list-item"><p class="zh">${zh}</p><p class="en">${enHtml}</p></li>`;
}

function replaceRequired(html, from, to) {
  if (!html.includes(from)) {
    throw new Error(`Expected source fragment not found: ${from.slice(0, 120)}`);
  }
  return html.replace(from, to);
}

const paragraphPairs = [
  [
    `In addition to addressing the interchange problem, USD also provides powerful mechanisms for large-scale collaboration and context-dependent asset refinement anywhere in a production pipeline. For example: `,
    `除了处理数据交换问题，USD 还为生产管线中的大规模协作和依赖上下文的资产细化提供强大的机制。例如：`,
  ],
  [
    `This set of documents describes the concrete Usd software package, its APIs, and their effective use. In contrast, the forthcoming <em>Composition Compendium</em> centers on USD composition's detailed semantics.`,
    `这组文档说明具体的 Usd 软件包、其 API 以及有效使用方式。相对地，计划中的 <em>Composition Compendium</em> 会聚焦 USD 组合的详细语义。`,
  ],
  [
    `Following is an overview of the architecture, followed by information for <a class="el" href="_usd__overview_and_purpose.html#Usd_Quickstart">getting started with USD</a>, and some <a class="el" href="_usd__overview_and_purpose.html#Usd_Background">background on how the USD project came to be.</a>`,
    `下面先给出架构概览，然后提供 <a class="el" href="_usd__overview_and_purpose.html#Usd_Quickstart">USD 入门</a> 信息，以及 <a class="el" href="_usd__overview_and_purpose.html#Usd_Background">USD 项目形成背景</a>。`,
  ],
  [
    `The USD repository is divided into four "core" packages, plus 3rd-party application plugins and extras:`,
    `USD 仓库分为四个“核心”包，另外还有第三方应用插件和额外内容：`,
  ],
  [
    `To author and consume USD, you need only the <em>base</em> and <em>usd</em> packages. Most of the open-source third-party plugins, however, do make use of <em>usdImaging</em> for fast preview, and as part of the answer to the question of what application XXX should do when it is asked to import a USD prim type of which it has no corresponding native representation. (Answer: it creates a proxy representation that delegates preview to usdImaging, and presents the prim's properties for inspection and overriding.)`,
    `要编写和消费 USD，只需要 <em>base</em> 与 <em>usd</em> 两个包。不过，大多数开源第三方插件会使用 <em>usdImaging</em> 来快速预览；当应用需要导入没有原生表示的 USD prim 类型时，它通常会创建代理表示，把预览委托给 usdImaging，并展示该 prim 的属性以便检查和覆盖。`,
  ],
  [
    `Following is a deeper indexing of the four packages.`,
    `下面按层次更深入地索引这四个包。`,
  ],
  [
    `The USD <em>package</em> begins with the low-level modules for path resolution, scene description serialization, and composition, upon which the "core" Usd module relies. The USD package is rounded out by a set of schema and utility modules that layer on top of the core. In low-to-high order, the modules are:`,
    `USD <em>package</em> 从路径解析、场景描述序列化和组合等低层模块开始，这些模块支撑“core” Usd 模块；其上再叠加 schema 与工具模块。按从低到高的顺序，模块如下：`,
  ],
  [
    `Usd includes python wrapping for all core classes and generated schema classes. Each module described in the last section, plus the core Usd module, are independently importable. Each module includes in-python help/documentation extracted from the doxygen docs for the module. We have chosen, initially, to keep the python API as true to the C++ API as possible, with one notable exception.`,
    `Usd 为所有核心类和生成的 schema 类提供 Python 封装。上一节描述的每个模块以及核心 Usd 模块都可以独立导入。每个模块都包含从该模块 Doxygen 文档抽取出的 Python 内帮助/文档。初始设计上，Python API 尽量忠实于 C++ API，但有一个明显例外。`,
  ],
  [
    `USD's central array type, used to hold all array-valued scene description types, is <a class="el" href="class_vt_array.html" title="Represents an arbitrary dimensional rectangular container class.">VtArray</a>. The python wrapping for <a class="el" href="class_vt_array.html" title="Represents an arbitrary dimensional rectangular container class.">VtArray</a> supports python's "buffer protocol", so <a class="el" href="class_vt_array.html" title="Represents an arbitrary dimensional rectangular container class.">VtArray</a> 's returned by USD to python can be trivially accessed like and converted to native python containers, as well as numpy arrays. Further, USD methods that expect a <a class="el" href="class_vt_array.html" title="Represents an arbitrary dimensional rectangular container class.">VtArray</a> input argument should always successfully convert native python containers and numpy arrays whose underlying element-type is compatible.`,
    `USD 用来保存所有数组值场景描述类型的核心数组类型是 <a class="el" href="class_vt_array.html" title="Represents an arbitrary dimensional rectangular container class.">VtArray</a>。<a class="el" href="class_vt_array.html" title="Represents an arbitrary dimensional rectangular container class.">VtArray</a> 的 Python 封装支持 Python “buffer protocol”，因此 USD 返回给 Python 的 <a class="el" href="class_vt_array.html" title="Represents an arbitrary dimensional rectangular container class.">VtArray</a> 可以像原生 Python 容器或 numpy 数组一样访问和转换；同时，期望 <a class="el" href="class_vt_array.html" title="Represents an arbitrary dimensional rectangular container class.">VtArray</a> 输入的 USD 方法，应能成功转换底层元素类型兼容的原生 Python 容器和 numpy 数组。`,
  ],
  [
    `Please visit <a href="http://openusd.org">the USD Documentation Hub</a> where you will find tutorials, FAQs, and other supporting material.`,
    `请访问 <a href="http://openusd.org">USD Documentation Hub</a>，其中包含教程、FAQ 和其他支持材料。`,
  ],
  [
    `The outward-facing goal of Universal Scene Description is to take the next step in DCC application data interchange <em>beyond</em> what is encodable in the ground-breaking Alembic interchange package. The chief component of that step is the ability to encode, interchange, and edit entire scenes with the ability to share variation and repeated/instanced scene data across shots and sequences, by providing robust asset-level (but not restricted to asset-level) file-referencing with sparse override capabilities. Additionally, USD provides a handful of other "composition operators" and concepts that target:`,
    `Universal Scene Description 面向外部的目标，是在突破性的 Alembic 交换包可表达内容之外，推动 DCC 应用数据交换再进一步。关键能力是编码、交换和编辑完整场景，并通过健壮的资产级文件引用和稀疏覆盖能力，在镜头与序列之间共享变体以及重复/实例化的场景数据。此外，USD 还提供若干“composition operators”和概念，目标包括：`,
  ],
  [
    `The USD project also developed under a high priority inward-facing mandate to simplify and unify Pixar's binary cache-based geometry package (TidScene) with its ASCII, animation and rigging scene description and composition system (Presto core). This mandate required that the advanced rigging concepts and datatypes of Presto be layerable on top of a reduced-featureset, shared (with USD) core. Given the time and resource constraints, and necessity to not massively disrupt our in-use codebase, we chose to largely retain our existing data model, while looking to Alembic as a guide for many schema decisions along the way. While it is unlikely Pixar will attempt to expand the Alembic API and core to encompass USD composition, asset resolution, and necessary plugin mechanisms, we are committed to providing a USD "file format" plugin that allows the USD core and toolset to consume and author Alembic files as if they were native USD files (obviously writing cannot always produce an equally meaningful Alembic file because composition operators cannot be represented in Alembic).`,
    `USD 项目也承担了一个高优先级的内部任务：简化并统一 Pixar 基于二进制缓存的几何包 TidScene，以及其 ASCII、动画和绑定场景描述与组合系统 Presto core。这个任务要求 Presto 的高级绑定概念和数据类型能够叠加在功能缩减、与 USD 共享的核心之上。受时间、资源和不能大幅扰动现有代码库的限制，Pixar 大体保留了原有数据模型，同时在许多 schema 决策中参考 Alembic。虽然 Pixar 不太可能扩展 Alembic API 和核心来包含 USD 组合、资产解析和必要插件机制，但 USD 会提供一个“file format”插件，让 USD core 和 toolset 能像处理原生 USD 文件一样消费和创作 Alembic 文件；当然，由于 Alembic 无法表示 composition operators，写出结果并不总能产生同等语义的 Alembic 文件。`,
  ],
];

const listPairs = [
  [`<b>layers</b> enable artists in different departments to all work simultaneously on the same "thing", whether that be a singular asset, an aggregate asset, a sequence, or a shot. `, `<b>layers</b> 允许不同部门的艺术家同时处理同一个“对象”，这个对象可以是单个资产、聚合资产、序列或镜头。`],
  [`<b>variants</b> enable asset creators to package up an enumerated set of variations, which can be selected and re-selected by downstream artists in consuming contexts. Using variants in combination with the <b>inherits</b> composition operator, a downstream artist can introduce <em>new</em> variations for all instances of an asset, in a particular (set, sequence, shot, etc.) context. Abilities like this can dramatically reduce the number of pipeline-stalling "asset fix requests" needed to support downstream artists.`, `<b>variants</b> 让资产创建者把一组枚举变体打包起来，供下游艺术家在消费上下文中选择和重新选择。variants 与 <b>inherits</b> composition operator 结合时，下游艺术家可以在特定集合、序列或镜头上下文中，为资产的所有实例引入<em>新的</em>变体，从而显著减少阻塞管线的“资产修复请求”。`],
  [`<b>base</b> - Contains application-agnostic, foundation modules, upon which most Pixar software builds, including possible future open-source projects.`, `<b>base</b> - 包含与应用无关的基础模块，Pixar 的大多数软件都构建在其上，未来可能开源的项目也可复用它。`],
  [`<b>usd</b> - Contains all the modules directly related to authoring, reading, and composing universal scene description. Defines the plugin interfaces by which USD can be extended and adapted.`, `<b>usd</b> - 包含与创作、读取和组合 universal scene description 直接相关的所有模块，并定义 USD 扩展与适配所需的插件接口。`],
  [`<b>imaging</b> - Contains the embeddable Hydra hardware renderer as well as other low-level, imaging-related services.`, `<b>imaging</b> - 包含可嵌入的 Hydra 硬件渲染器，以及其他低层成像相关服务。`],
  [`<b>usdImaging</b> - Ties usd and hydra together by providing an adapter to Hydra that reads data directly and efficiently from a <a class="el" href="class_usd_stage.html" title="The outermost container for scene description, which owns and presents composed prims as a scenegraph...">UsdStage</a>. Defines a plugin interface by which the adapter can be extended, and provides <em>usdview</em> , the standalone graphical USD inspector tool.`, `<b>usdImaging</b> - 通过 Hydra 适配器把 usd 与 hydra 连接起来，该适配器能从 <a class="el" href="class_usd_stage.html" title="The outermost container for scene description, which owns and presents composed prims as a scenegraph...">UsdStage</a> 直接且高效地读取数据；它还定义适配器扩展所需的插件接口，并提供独立图形化 USD 检查工具 <em>usdview</em>。`],
  [`<b>third_party</b> - Contains USD plugins for DCC applications.`, `<b>third_party</b> - 包含面向 DCC 应用的 USD 插件。`],
  [`<b>extras</b> - Contains a collection of tutorial material, sample code, and small example USD assets.`, `<b>extras</b> - 包含教程材料、示例代码和小型 USD 示例资产。`],
  [`<a class="el" href="arch_page_front.html">Arch: Architecture Dependent</a> module centralizes functionality that must be implemented differently for different operating systems or architectures, so that we can avoid littering the entire code-base with conditionally-compiled code.`, `<a class="el" href="arch_page_front.html">Arch: Architecture Dependent</a> 模块集中管理因操作系统或架构不同而必须差异化实现的功能，避免在整个代码库中散布条件编译代码。`],
  [`<a class="el" href="tf_page_front.html">Tf: Tools Foundations</a> module is a catch-all for low-level, commonly used services developed at Pixar, including facilities for memory tracking, error reporting and debugging, string utilities, Python wrapping aids, threading/synchronization tools, registry and singleton management, smart pointers, and "observer pattern" support, which we call "notification".`, `<a class="el" href="tf_page_front.html">Tf: Tools Foundations</a> 模块汇集 Pixar 开发的低层通用服务，包括内存跟踪、错误报告与调试、字符串工具、Python 包装辅助、多线程/同步工具、注册表与单例管理、智能指针，以及称为 “notification” 的观察者模式支持。`],
  [`<a class="el" href="gf_page_front.html">Gf : Graphics Foundations</a> module provides Pixar's equivalent to imath, and provides many of the types enumerated in Vt. It also provides other foundational graphics abstractions like frusta and a camera model. Given unlimited resources we would have replaced our use of the linear algebra components in Gf with imath, but Gf's use in Pixar's code-base is substantial and its API's do not map one-to-one to imath.`, `<a class="el" href="gf_page_front.html">Gf : Graphics Foundations</a> 模块提供 Pixar 对应 imath 的图形基础能力，也提供 Vt 中枚举的许多类型，以及视锥体、相机模型等图形基础抽象。由于 Gf 在 Pixar 代码库中使用很深，且 API 不能与 imath 一一映射，因此保留了 Gf 的线性代数组件。`],
  [`<a class="el" href="js_page_front.html">Js: JSON I/O</a> module provides a thin API wrapper on top of the <a href="http://rapidjson.org/">RapidJSON</a> package, which is what our plugin system uses for multi-threaded plugin discovery.`, `<a class="el" href="js_page_front.html">Js: JSON I/O</a> 模块在 <a href="http://rapidjson.org/">RapidJSON</a> 包之上提供轻量 API 包装，插件系统用它进行多线程插件发现。`],
  [`trac_page_front module provides an interface for embeddable performance-profiling tagging.`, `trac_page_front 模块提供可嵌入性能分析标记的接口。`],
  [`<a class="el" href="vt_page_front.html">Vt : Value Types</a> module provides many of the concrete types that Sdf is able to recognize and serialize. It provides a copy-on-write array-type, <a class="el" href="class_vt_array.html" title="Represents an arbitrary dimensional rectangular container class.">VtArray</a>, which is used for all array types in Usd, and an efficient type-erasure wrapper class, <a class="el" href="class_vt_value.html" title="Provides a container which may hold any type, and provides introspection and iteration over array typ...">VtValue</a>, that also provides datatype conversion facilities and support for unboxing Python objects. <a class="el" href="class_vt_value.html" title="Provides a container which may hold any type, and provides introspection and iteration over array typ...">VtValue</a> is supported in all Usd API for getting and setting values.`, `<a class="el" href="vt_page_front.html">Vt : Value Types</a> 模块提供 Sdf 能识别和序列化的许多具体类型。它提供 copy-on-write 数组类型 <a class="el" href="class_vt_array.html" title="Represents an arbitrary dimensional rectangular container class.">VtArray</a>，用于 Usd 中所有数组类型；还提供高效的类型擦除包装类 <a class="el" href="class_vt_value.html" title="Provides a container which may hold any type, and provides introspection and iteration over array typ...">VtValue</a>，支持数据类型转换和 Python 对象拆箱。所有 Usd 取值和设值 API 都支持 <a class="el" href="class_vt_value.html" title="Provides a container which may hold any type, and provides introspection and iteration over array typ...">VtValue</a>。`],
  [`<a class="el" href="work_page_front.html">Work : Multi-threaded Dispatch</a> module provides a thin abstraction layer on top of Intel's TBB (Thread Building Blocks), and is leveraged extensively in Usd core and higher-level services for multi-threading.`, `<a class="el" href="work_page_front.html">Work : Multi-threaded Dispatch</a> 模块在 Intel TBB (Thread Building Blocks) 之上提供轻量抽象层，Usd core 和更高层服务广泛用它实现多线程。`],
  [`<a class="el" href="plug_page_front.html">Plug: Plugin Framework</a> module provides the organization and access API for all plugins. It identifies plugins by the existence of a plugInfo.json manifest file, which enumerates the number and kinds of plugins provided by a module.`, `<a class="el" href="plug_page_front.html">Plug: Plugin Framework</a> 模块提供所有插件的组织和访问 API。它通过 plugInfo.json manifest 文件识别插件，该文件枚举模块提供的插件数量和类型。`],
  [`<a class="el" href="ar_page_front.html">Ar: Asset Resolution</a> module defines the abstract interface for USD's asset resolution plugin, so that clients can author asset references in their USD files that make sense to their asset management systems. It also provides a "fallback resolver" that is active when no site-level plugin has been provided; the fallback resolver provides basic search-path based resolution.`, `<a class="el" href="ar_page_front.html">Ar: Asset Resolution</a> 模块定义 USD 资产解析插件的抽象接口，让客户端能在 USD 文件中编写符合其资产管理系统语义的资产引用。它也提供在没有站点级插件时启用的 “fallback resolver”，以基于搜索路径的方式完成基本解析。`],
  [`<a class="el" href="kind_page_front.html">Kind : Extensible Categorization</a> module provides a simple, site-extensible token-based typing system, which USD uses, for example, to identify and classify types of "models".`, `<a class="el" href="kind_page_front.html">Kind : Extensible Categorization</a> 模块提供简单且站点可扩展的 token 类型系统，USD 可用它识别和分类 “models” 等类型。`],
  [`<a class="el" href="sdf_page_front.html">Sdf : Scene Description Foundations</a> module defines the Usd data model, namely: prims, attributes, relationships, meta-data, as well as the concrete types that attributes can possess. Sdf also provides the key abstraction <a class="el" href="class_sdf_layer.html" title="A scene description container that can combine with other such containers to form simple component as...">SdfLayer</a>, which represents a file of data subscribing to the Usd data model, and provides low-level data authoring and extraction API's. <a class="el" href="class_sdf_layer.html" title="A scene description container that can combine with other such containers to form simple component as...">SdfLayer</a> also has an associated plugin mechanism known as <a class="el" href="class_sdf_file_format.html" title="Base class for file format implementations.">SdfFileFormat</a> that allows any reasonable file format to be dynamically translated into Usd; it is via this mechanism that we added a binary encoding to the pre-existing ASCII format for Usd, as well as how we support referencing and reading of Alembic files.`, `<a class="el" href="sdf_page_front.html">Sdf : Scene Description Foundations</a> 模块定义 Usd 数据模型，包括 prims、attributes、relationships、meta-data，以及 attribute 可拥有的具体类型。Sdf 还提供关键抽象 <a class="el" href="class_sdf_layer.html" title="A scene description container that can combine with other such containers to form simple component as...">SdfLayer</a>，表示遵循 Usd 数据模型的数据文件，并提供低层数据创作和抽取 API。<a class="el" href="class_sdf_layer.html" title="A scene description container that can combine with other such containers to form simple component as...">SdfLayer</a> 还有名为 <a class="el" href="class_sdf_file_format.html" title="Base class for file format implementations.">SdfFileFormat</a> 的插件机制，可把合理的文件格式动态转换为 Usd；USD 也通过这一机制为原有 ASCII 格式加入二进制编码，并支持引用和读取 Alembic 文件。`],
  [`<a class="el" href="pcp_page_front.html">Pcp : PrimCache Population (Composition)</a> module implements the composition logic at the heart of USD; Pcp efficiently builds and caches an "index cache" that the Usd scenegraph uses to determine which prims need to be populated, and where to look for values for any particular property in a multi-layer aggregation of assets.`, `<a class="el" href="pcp_page_front.html">Pcp : PrimCache Population (Composition)</a> 模块实现 USD 核心的组合逻辑；Pcp 高效构建并缓存 “index cache”，Usd scenegraph 用它判断需要填充哪些 prim，以及在多层资产聚合中到哪里查找特定 property 的值。`],
  [`<a class="el" href="usd_page_front.html">Usd : Universal Scene Description (Core)</a> module builds the USD scene-graph (<a class="el" href="class_usd_stage.html" title="The outermost container for scene description, which owns and presents composed prims as a scenegraph...">UsdStage</a>), and provides the primary API's for authoring and reading composed scene description. The Usd module and the concepts it contains are meant to be fairly generic, allowing many different domain-specific schemas to be built over it, as the USD package does for geometry, shading, etc. We make an exception for two particular concepts/schemas, "Model" and "AssetInfo", which are defined in the core Usd module, because they are extremely valuable for organizing scene description, and other core behaviors are built on top of the concept of Model.`, `<a class="el" href="usd_page_front.html">Usd : Universal Scene Description (Core)</a> 模块构建 USD scene-graph (<a class="el" href="class_usd_stage.html" title="The outermost container for scene description, which owns and presents composed prims as a scenegraph...">UsdStage</a>)，并提供创作和读取组合后场景描述的主要 API。Usd 模块及其中概念设计得较通用，便于在其上构建多种领域 schema，例如 geometry、shading 等。例外是核心 Usd 模块中定义了 “Model” 和 “AssetInfo” 两个概念/schema，因为它们对于组织场景描述极有价值，且其他核心行为也建立在 Model 概念之上。`],
  [`<a class="el" href="usd_geom_page_front.html">UsdGeom : USD Geometry Schema</a> : The primary graphics-supporting schema module for DCC interchange, UsdGeom provides geometric primitives (meshes, curves, patches, xforms, etc.), as well as a Camera schema and "Primvars" that encode UV's and various user-defined fields over a primitive. The majority of the schema classes are produced entirely via the <em>usdGenSchema</em> code generator included with the core.`, `<a class="el" href="usd_geom_page_front.html">UsdGeom : USD Geometry Schema</a> 是支持 DCC 交换的主要图形 schema 模块，提供几何 primitive（meshes、curves、patches、xforms 等）、Camera schema，以及用于在 primitive 上编码 UV 和各类用户字段的 “Primvars”。大多数 schema 类完全由 core 中的 <em>usdGenSchema</em> 代码生成器生成。`],
  [`<a class="el" href="usd_physics_page_front.html">UsdPhysics : USD Physics Schema</a> : The primary physics-supporting schema module, UsdPhysics provides physics description of the USD prims (rigid bodies, joints, scenes, collisions, etc.). Physics schema also defines physics related metrics like the mass units, kilogramsPerUnit (<a class="el" href="struct_usd_physics_tokens_type.html#a24c37003b1414e39167b1132f765dfec">UsdPhysicsTokensType::kilogramsPerUnit</a>).`, `<a class="el" href="usd_physics_page_front.html">UsdPhysics : USD Physics Schema</a> 是主要的物理 schema 模块，提供 USD prims 的物理描述（rigid bodies、joints、scenes、collisions 等）。Physics schema 也定义与物理相关的度量，例如质量单位 kilogramsPerUnit (<a class="el" href="struct_usd_physics_tokens_type.html#a24c37003b1414e39167b1132f765dfec">UsdPhysicsTokensType::kilogramsPerUnit</a>)。`],
  [`<a class="el" href="usd_shade_page_front.html">UsdShade : USD Shading Schema</a> Schema module that defines Looks, Shaders, connectible Parameters, with API for building shading networks and user-facing "Look Interfaces" that allow shading networks to be shared (via instancing) by multiple Looks. UsdShade also prescribes how geometry is <em>bound</em> to Looks. With just the objects in UsdShade one can encode completely generic shading; however, it also allows renderer-specific shading schemas to be built on top of it, and a Look can host the network "terminals" for any number of renderer schemas.`, `<a class="el" href="usd_shade_page_front.html">UsdShade : USD Shading Schema</a> 模块定义 Looks、Shaders 和可连接 Parameters，并提供构建 shading networks 的 API，以及面向用户的 “Look Interfaces”，让多个 Looks 能通过实例化共享 shading networks。UsdShade 还规定 geometry 如何与 Looks <em>绑定</em>。仅使用 UsdShade 对象就可以编码通用 shading；同时也允许在其上构建渲染器特定的 shading schemas，一个 Look 可以承载任意数量 renderer schemas 的 network “terminals”。`],
  [`<a class="el" href="usd_ri_page_front.html">UsdRi: USD RenderMan Utilities</a> module for data targeted at Pixar's RenderMan specification. Includes shading schemas for both RSL and RIS shading systems, as well as a "catch all" <code>RiStatements</code> schema for encoding various RenderMan concepts/directives, such as attributes, options, coordinate systems, etc.`, `<a class="el" href="usd_ri_page_front.html">UsdRi: USD RenderMan Utilities</a> 模块面向 Pixar RenderMan 规范中的数据，包含 RSL 与 RIS shading 系统的 shading schemas，以及用于编码各类 RenderMan 概念/指令的通用 <code>RiStatements</code> schema，例如 attributes、options、coordinate systems 等。`],
  [`<a class="el" href="usd_utils_page_front.html">UsdUtils: USD Utilities</a> module provides a number of utilities and conventions that have proven useful in a USD-based pipeline.`, `<a class="el" href="usd_utils_page_front.html">UsdUtils: USD Utilities</a> 模块提供在 USD-based pipeline 中已被证明有用的一组工具和约定。`],
  [`<b>Garch</b> : The Graphics Architecture module provides abstractions for architecture-specific functionality that may pull in imaging-related dependencies.`, `<b>Garch</b> : Graphics Architecture 模块为可能引入 imaging 相关依赖的架构特定功能提供抽象。`],
  [`<b>Glf</b> : The GL Foundations module provides access to textures, ptextures and GL resources (such as draw targets). It also provides some basic glsl shaders used by hdSt.`, `<b>Glf</b> : GL Foundations 模块提供对 textures、ptextures 和 GL 资源（例如 draw targets）的访问，也提供 hdSt 使用的一些基础 glsl shaders。`],
  [`<b>Hio</b> : The Hydra Resource I/O module provides resource loaders used by Hydra, such as Pixar's shader container format (glslfx). It will eventually house the infrastructure for image loading that is currently parked in Glf.`, `<b>Hio</b> : Hydra Resource I/O 模块提供 Hydra 使用的资源加载器，例如 Pixar 的 shader container format (glslfx)。未来它会容纳当前暂放在 Glf 中的图像加载基础设施。`],
  [`<b>CameraUtil</b> The Camera Utilities module provides a small but important set of common camera-related computations that don't really belong in the core <a class="el" href="class_gf_camera.html" title="Object-based representation of a camera.">GfCamera</a> class.`, `<b>CameraUtil</b> Camera Utilities 模块提供一小组重要的相机相关通用计算，这些计算并不适合放在核心 <a class="el" href="class_gf_camera.html" title="Object-based representation of a camera.">GfCamera</a> 类中。`],
  [`<b>PxOsd</b> : The Pixar OpenSubdiv module provides some higher-level utilities on top of OpenSubdiv that may, one day make it into OpenSubdiv, but are still "cooking". Hydra interacts with OpenSubdiv through pxOsd.`, `<b>PxOsd</b> : Pixar OpenSubdiv 模块在 OpenSubdiv 之上提供一些更高层工具，这些工具未来可能进入 OpenSubdiv，但目前仍在演进中。Hydra 通过 pxOsd 与 OpenSubdiv 交互。`],
  [`<b>Hd</b> : The Hydra module provides the Hydra renderer. Hydra uses OpenSubdiv for tessellating subdivision meshes, and supports general programmable glsl shaders, and multiple render passes.`, `<b>Hd</b> : Hydra 模块提供 Hydra renderer。Hydra 使用 OpenSubdiv 对 subdivision meshes 进行细分，并支持通用可编程 glsl shaders 和多 render passes。`],
  [`<b>Hdx</b> : The Hydra Extensions module provides higher-level functionality on top of Hydra, such as organization and packaging for particular kinds of multiple render-pass tasks.`, `<b>Hdx</b> : Hydra Extensions 模块在 Hydra 之上提供更高层功能，例如对特定多 render-pass 任务的组织和封装。`],
  [`<a class="el" href="usd_app_utils_page_front.html">UsdAppUtils: USD Application Utilities</a> : A library that provides a number of utilities and common functionality for applications that view and/or record images of UsdStages.`, `<a class="el" href="usd_app_utils_page_front.html">UsdAppUtils: USD Application Utilities</a> : 这是一个库，为查看和/或记录 UsdStages 图像的应用提供多种工具和通用功能。`],
  [`<b>UsdImaging</b> : An adapter to Pixar's modern, high-performance GL rendering engine <em>Hydra</em> (which in turn leverages OpenSubdiv) that provides preview imaging (including streaming playback) for any <a class="el" href="class_usd_stage.html" title="The outermost container for scene description, which owns and presents composed prims as a scenegraph...">UsdStage</a> encoded with UsdGeom and UsdShade. UsdImaging takes full advantage of scenegraph instancing in USD, and uses multiple threads to extract data from a <a class="el" href="class_usd_stage.html" title="The outermost container for scene description, which owns and presents composed prims as a scenegraph...">UsdStage</a> and marshal it into Hd objects.`, `<b>UsdImaging</b> : 这是 Pixar 现代高性能 GL 渲染引擎 <em>Hydra</em> 的适配器（Hydra 又利用 OpenSubdiv），可为任何以 UsdGeom 和 UsdShade 编码的 <a class="el" href="class_usd_stage.html" title="The outermost container for scene description, which owns and presents composed prims as a scenegraph...">UsdStage</a> 提供预览成像（包括流式播放）。UsdImaging 充分利用 USD 中的 scenegraph instancing，并用多线程从 <a class="el" href="class_usd_stage.html" title="The outermost container for scene description, which owns and presents composed prims as a scenegraph...">UsdStage</a> 抽取数据，再整理为 Hd objects。`],
  [`<b>Usdviewq</b> : A python package that provides the controller and GUI elements used by usdview. The elements are structured for ease of embedding in other python applications, also.`, `<b>Usdviewq</b> : 一个 Python package，提供 usdview 使用的控制器和 GUI 元素；这些元素也按便于嵌入其他 Python 应用的方式组织。`],
  [`<b>Some underlying modules support more pythonic API's.</b> Some of the foundational modules shared with Presto, such as Sdf, provide a more pythonic API in which member-variable-like-things become properties in python. We have hesitated to deploy this level of pythonification at higher levels of the system because <a class="el" href="class_sdf_layer.html" title="A scene description container that can combine with other such containers to form simple component as...">SdfLayer</a> is the only container that truly owns its data: all the primary Usd-level classes represent restricted views on data that resides in one-or-more <a class="el" href="class_sdf_layer.html" title="A scene description container that can combine with other such containers to form simple component as...">SdfLayer</a> s, and don't possess any member variables/properties other than those that serve as temporary caches.`, `<b>一些底层模块支持更 Pythonic 的 API。</b> 与 Presto 共享的一些基础模块（例如 Sdf）提供更 Pythonic 的 API，在 Python 中类似成员变量的对象会成为属性。更高层系统没有大量采用这种 Python 化方式，是因为 <a class="el" href="class_sdf_layer.html" title="A scene description container that can combine with other such containers to form simple component as...">SdfLayer</a> 是唯一真正拥有数据的容器；主要 Usd 层级类都是一个或多个 <a class="el" href="class_sdf_layer.html" title="A scene description container that can combine with other such containers to form simple component as...">SdfLayer</a> 中数据的受限视图，除了临时缓存外并不拥有成员变量/属性。`],
  [`Encoding asset variation and preserving the ability to switch variants late in the pipeline`, `编码资产变体，并保留在管线后期切换 variants 的能力`],
  [`Scale to scenes of unlimited complexity by deferring reading of heavy property data until it is needed (as in Alembic), and also by providing composition semantics that allow deferred (and reversible) loading and composition of arbitrary amounts of scene description without sacrificing the ability to perform robust dependency analysis between prims in a scene. (See the discussion of <a class="el" href="_usd__page__best_practices.html#Usd_Payloads">payloads</a> for more information).`, `通过延迟读取重型 property 数据直到真正需要时才读取（类似 Alembic），并通过允许延迟且可逆地加载和组合任意数量场景描述的 composition semantics，扩展到无限复杂的场景，同时不牺牲对场景中 prim 之间依赖关系进行健壮分析的能力。（更多信息见 <a class="el" href="_usd__page__best_practices.html#Usd_Payloads">payloads</a> 讨论。）`],
  [`\n<a href="http://openusd.org">USD Home Page</a> `, `\n<a href="http://openusd.org">USD 首页 / USD Home Page</a> `],
];

const headingPairs = [
  [`<div class="headertitle"><div class="title">Overview and Purpose </div></div>`, `<div class="headertitle"><div class="title"><span class="zh">概述与目的</span><span class="en">Overview and Purpose</span></div></div>`],
  [`<h1><a class="anchor" id="Usd_ArchitecturalOverview"></a>\nArchitectural Overview</h1>`, `<h1><a class="anchor" id="Usd_ArchitecturalOverview"></a><span class="zh">架构概览</span><span class="en">Architectural Overview</span></h1>`],
  [`<h2><a class="anchor" id="Usd_Package_Base"></a>\nThe "base" package</h2>`, `<h2><a class="anchor" id="Usd_Package_Base"></a><span class="zh">“base” 包</span><span class="en">The "base" package</span></h2>`],
  [`<h2><a class="anchor" id="Usd_Package_Usd"></a>\nThe "usd" package</h2>`, `<h2><a class="anchor" id="Usd_Package_Usd"></a><span class="zh">“usd” 包</span><span class="en">The "usd" package</span></h2>`],
  [`<h2><a class="anchor" id="Usd_Package_Imaging"></a>\nThe "imaging" package</h2>`, `<h2><a class="anchor" id="Usd_Package_Imaging"></a><span class="zh">“imaging” 包</span><span class="en">The "imaging" package</span></h2>`],
  [`<h2><a class="anchor" id="Usd_Package_UsdImaging"></a>\nThe "usdImaging" package</h2>`, `<h2><a class="anchor" id="Usd_Package_UsdImaging"></a><span class="zh">“usdImaging” 包</span><span class="en">The "usdImaging" package</span></h2>`],
  [`<h1><a class="anchor" id="Usd_PythonSupport"></a>\nPython Support, numpy, etc.</h1>`, `<h1><a class="anchor" id="Usd_PythonSupport"></a><span class="zh">Python 支持、numpy 等</span><span class="en">Python Support, numpy, etc.</span></h1>`],
  [`<h1><a class="anchor" id="Usd_Quickstart"></a>\nQuickstart!</h1>`, `<h1><a class="anchor" id="Usd_Quickstart"></a><span class="zh">快速开始</span><span class="en">Quickstart!</span></h1>`],
  [`<h1><a class="anchor" id="Usd_Background"></a>\nUSD: What's the Point, and Why Isn't it Alembic ?</h1>`, `<h1><a class="anchor" id="Usd_Background"></a><span class="zh">USD 的意义是什么，为什么它不是 Alembic？</span><span class="en">USD: What's the Point, and Why Isn't it Alembic ?</span></h1>`],
  [`<h1><a class="anchor" id="Usd_Related"></a>\nRelated Pages</h1>`, `<h1><a class="anchor" id="Usd_Related"></a><span class="zh">相关页面</span><span class="en">Related Pages</span></h1>`],
];

let html = await readFile(sourcePath, "utf8");
html = `<!-- Generated API adjacent bilingual entry from source/openusd_api_overview_and_purpose_source.html. Source URL: https://openusd.org/release/api/_usd__overview_and_purpose.html -->\n${html}`;
html = html.replace("<html xmlns=\"http://www.w3.org/1999/xhtml\">", "<html xmlns=\"http://www.w3.org/1999/xhtml\" lang=\"zh-CN\">");
html = html.replace("<title>Universal Scene Description: Overview and Purpose</title>", "<title>Universal Scene Description: 概述与目的 / Overview and Purpose</title>");
html = html.replace('<link rel="shortcut icon" href="https://openusd.org/images/USDIcon.ico"/>', '<link rel="shortcut icon" href="images/USDIcon.ico"/>');
html = html.replace('<link href="usd_style.css" rel="stylesheet" type="text/css"/>', '<link href="usd_style.css" rel="stylesheet" type="text/css"/>\n<link href="openusd_cn.css?v=301" rel="stylesheet" type="text/css"/>');
html = html.replace('<script type="text/javascript" src="navtree.js"></script>', '<script type="text/javascript" src="navtree.js"></script>\n<script type="text/javascript" src="openusd_local_navtree.js"></script>');
html = html.replace("initMenu('',true,false,'search.php','Search');", "initMenu('',true,false,'search.php','Search');");

for (const [from, to] of headingPairs) {
  html = replaceRequired(html, from, to);
}

const scopeNote = `<div class="cn-repro-note">
<p class="zh">本页是 API 首页的相邻概念入口，保留官方 Doxygen 结构、英文原文、API 名称和链接目标，并在主要段落与模块说明前补充中文解释。</p>
<p class="en">This page is an adjacent conceptual entry from the API home page. It preserves the official Doxygen structure, English source text, API names, and link targets while adding Chinese explanations before key paragraphs and module descriptions.</p>
</div>`;
html = replaceRequired(html, `<div class="contents">\n<div class="textblock">`, `<div class="contents">\n<div class="textblock">\n${scopeNote}`);

for (const [en, zh] of paragraphPairs) {
  html = replaceRequired(html, `<p>${en}</p>`, bilingualBlock(zh, en));
}

for (const [en, zh] of listPairs) {
  html = replaceRequired(html, `<li>${en}</li>`, bilingualLi(zh, en));
}

html = html.replace(
  `</ul>\n</div>\n</body>\n</html>`,
  `</ul>\n</div>\n</body>\n</html>`,
);
html = html.replace(
  `<li class="footer">&copy; Copyright 2026, Pixar Animation Studios. | <a href="https://disneytermsofuse.com/">Terms of Use</a> | Generated on Wed Apr 22 2026 16:02:16 by <a href="https://www.doxygen.org/index.html"><img class="footer" src="doxygen.svg" width="104" height="31" alt="doxygen"/></a> 1.9.6 </li>`,
  `<li class="footer">&copy; Copyright 2026, Pixar Animation Studios. | <span class="cn-footer-note">中文双语复刻层：API 相邻概念入口，本地学习用途，官方英文正文与链接保留。 / Bilingual API adjacent-entry layer for local study; official English body and links are preserved.</span> | <a href="https://disneytermsofuse.com/">Terms of Use</a> | Generated on Wed Apr 22 2026 16:02:16 by <a href="https://www.doxygen.org/index.html"><img class="footer" src="doxygen.svg" width="104" height="31" alt="doxygen"/></a> 1.9.6 </li>`,
);

await mkdir(siteDir, { recursive: true });
await writeFile(outputPath, html, "utf8");

console.log(JSON.stringify({
  output: outputPath,
  translatedParagraphs: paragraphPairs.length,
  translatedListItems: listPairs.length,
  translatedHeadings: headingPairs.length,
}, null, 2));
